In [ ]:
import numpy as np

In [2]:
import numpy as np
print(np.__version__)

2.5.1


In [3]:
!uv pip list | findstr numpy

numpy                   2.5.1


In [4]:
%time sum(range(10000000))

CPU times: total: 219 ms
Wall time: 223 ms


49999995000000

In [7]:
np.arange(10)

#numpy를 이용한 계산
%time np.sum(np.arange(10000000))


CPU times: total: 46.9 ms
Wall time: 44.3 ms


np.int64(49999995000000)

In [10]:
import numpy as np

arr = np.array(
    ([1,2,3],
    [4,5,6])            # (()) <= 2차원. (두개있으므로)
)


print('배열의 차원:', arr.ndim, np.nidim(arr))  

AttributeError: module 'numpy' has no attribute 'nidim'

In [ ]:
import numpy as np

# 2행 3열의 수치형 2차원 배열 정의
arr = np.array([
    [1,2,3],
    [4,5,6]            # (()) <= 2차원. (두개있으므로)
])

print("배열의 차원:", arr.ndim, np.ndim(arr))   # 출력: 2
print("배열의 형태:", arr.shape, np.shape(arr))  # 출력: (2, 3)
print("원소 총 개수:", arr.size, np.size(arr))  # 출력: 6
print("데이터 타입:", arr.dtype)  # 출력: int64

# 정수형 데이터를 실수형(Float) 데이터 타입으로 강제 변환
float_arr = arr.astype(np.float64)
print("변경된 타입:", float_arr.dtype)  # 출력: float64


배열의 차원: 2 2
배열의 형태: (2, 3) (2, 3)
원소 총 개수: 6 6
데이터 타입: int64
변경된 타입: float64


In [13]:
import numpy as np

a = np.array([1,2,3])
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


In [14]:
import numpy as np

int64_a = np.array([1, 2, 3])
print(int64_a.dtype )
float32_b = int64_a.astype(np.float32)
print(float32_b )                 # array([1., 2., 3.])
print(float32_b .dtype)           # dtype('float32')

int64
[1. 2. 3.]
float32


In [16]:
a = np.array([1,2,3])
print(dir(a))
print(type(a))
print(a.shape)

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__'

In [18]:
b = np.array([
    [1,2,],
    [3,4]
])

print(b)
print(dir(b))
print(type(b))
print(b.shape)

[[1 2]
 [3 4]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd

In [32]:
c = np.array([
    [
        [1,2],
        [3,4]    ],
        [
            [5,6],
            [7,8]
        ]
])

print(c)
print(dir(c))
print(type(c))
print(c.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__

In [23]:
a = np. zeros(3)
print(a)

[0. 0. 0.]


In [26]:
a = np.zeros( (2,3 ))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [27]:
a = np.zeros( [2,3] )
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [30]:
a = np.ones(3)
print(a)

[1. 1. 1.]


In [31]:
a = np.ones( [2,3])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [33]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
a = np.eye(3,4, k=0)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [37]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a = np.identity(5)      # 정방행렬
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [40]:
a = np.full( (2,2), 1 )
print(a)

[[1 1]
 [1 1]]


In [41]:
a = np.full( (2,2), [3,4] )
print(a)

[[3 4]
 [3 4]]


In [47]:
a = np.full( (3,4), [1,2,4,3] )
print(a)

[[1 2 4 3]
 [1 2 4 3]
 [1 2 4 3]]


# 텐서 !

In [49]:
a = np.full( (2,2), [[1], [2] ] )
print(a)

[[1 1]
 [2 2]]


In [50]:
a = np.full((2,2), [[1,2],[3,4]])  # np.full(shape, fill_value)
print(a)                     # [[1 2][3 4]]

[[1 2]
 [3 4]]


In [51]:
e = np.empty(3)
print(a)

[[1 2]
 [3 4]]


In [52]:
a = np.linspace(0,49)
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]


In [54]:
a = np.linspace(0,5)
print(a)

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]


In [57]:
a = np.linspace(0,4, endpoint = False)
print(a)

[0.   0.08 0.16 0.24 0.32 0.4  0.48 0.56 0.64 0.72 0.8  0.88 0.96 1.04
 1.12 1.2  1.28 1.36 1.44 1.52 1.6  1.68 1.76 1.84 1.92 2.   2.08 2.16
 2.24 2.32 2.4  2.48 2.56 2.64 2.72 2.8  2.88 2.96 3.04 3.12 3.2  3.28
 3.36 3.44 3.52 3.6  3.68 3.76 3.84 3.92]


In [58]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [59]:
arr = np.arange(3,10)
print(arr)

[3 4 5 6 7 8 9]


In [60]:
arr = np.arange(3,10,2)
print(arr)

[3 5 7 9]


In [61]:
arr = np.arange(0,1,0.2)
print(arr)

[0.  0.2 0.4 0.6 0.8]


In [63]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

print(a)

b = np.ones_like(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [1 1 1]]


In [64]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

print(a)

b = np.empty_like(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [67]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

print(a)

b = np.zeros_like(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[0 0 0]
 [0 0 0]]


In [68]:
a = np.random.rand(2,3)
print(a)

[[0.61037785 0.44035585 0.55161928]
 [0.50679387 0.48912909 0.27050616]]


In [69]:
a = np.random.randn(2,3)
print(a)

[[-1.46902829  0.412999   -0.20224848]
 [-1.58627453 -0.23486455 -1.09735935]]


In [73]:
np.random.randint(2,3,3)

array([2, 2, 2], dtype=int32)

In [70]:
sum?

Signature: sum(iterable, /, start=0)
Docstring:
Return the sum of a 'start' value (default: 0) plus an iterable of numbers

When the iterable is empty, return the start value.
This function is intended specifically for use with numeric values and may
reject non-numeric types.
Type:      builtin_function_or_method

In [71]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers

    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [72]:
np.array?

Signature:
np.array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None,
)
Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      ndmax=0, like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    require

## shadow copy

In [74]:
a = [1,2,3]
b = a
print(b)
print(a is b)

[1, 2, 3]
True


In [75]:
b[0] = 7
print(a)
print(b)
print(a is b)

[7, 2, 3]
[7, 2, 3]
True


## Deep copy = 다른 메모리를 사용하는것

In [77]:
a = [1,2,3]
b = a.copy()
print( id(a) )
print( id(b) )

2203583868800
2203585709824


In [78]:
print( a is b )
print( a == b)

False
True


In [81]:
b[0] = 8
print(a)
print(b)

print(a is b)
print(a == b)

[1, 2, 3]
[8, 2, 3]
False
False


## 2차원 LIST에 대한 .COPY ()    "
= 실제 요소에 대해서는 Deep copy 가 안됨 = 실제 (요소)값을 가르키는 주소는 그대로임.

In [83]:
import copy

a= [[1,2,3]]
b = copy.deepcopy(a)

print(a[0] is b[0] )
print( a[0] == b[0])

b[0][0] = 10

print(a[0] is b[0] )
print( a[0] == b[0])

False
True
False
False


In [85]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr[arr > 5])

bool_mask = arr<5
print(arr[bool_mask])

[6 7 8 9]
[1 2 3 4]


In [ ]:
 a = np.arange(24).reshape(2,3,4)       # 2층 [3행, 4열]        # 층이 나누어져있으면, 빈 줄이 하나 생겨서 출력된다.
 print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [92]:
# fancy indexing은 원래 3차원 그대로 가져온다.
a[[0]]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [93]:
# indexing은 차원이 하나 감소해서 가져온다. (3차원을 2차원으로 가져온다.)
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
# ellipsis

print(a[0,...])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [94]:
print(a[0,:,:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [95]:
type(...)   # ellipsis

ellipsis

In [102]:
a = np.array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [99]:
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [100]:
a[[0], :, [1,3]]

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [106]:
 a = np.arange(24).reshape(2,3,4)       # 2층 [3행, 4열]        # 층이 나누어져있으면, 빈 줄이 하나 생겨서 출력된다.
 print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [110]:
b = a[:, [1], :]
print(b)

[[[ 4  5  6  7]]

 [[16 17 18 19]]]


In [112]:
b.shape

(2, 1, 4)

In [117]:
c = a[ [1], :, :]
print(c)

[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [118]:
c.shape

(1, 3, 4)

In [124]:
print( a[:,:,[1] ] )

print('------------------------')
print( a[:,:,1] )

[[[ 1]
  [ 5]
  [ 9]]

 [[13]
  [17]
  [21]]]
------------------------
[[ 1  5  9]
 [13 17 21]]


In [131]:
np.set_printoptions(edgeitems=6)
#np.set_printoptions(edgeitems=6)

np.arange(10000)

array([   0,    1,    2,    3,    4,    5, ..., 9994, 9995, 9996, 9997,
       9998, 9999], shape=(10000,))

### flatten()은 메모리 공간을 새로 만들면서 변환

In [133]:
arr = np.array([
    [1,2],
    [3,4]
])

dap = arr.flatten()
print(dap)

[1 2 3 4]


In [136]:
print(f'메모리 공유 확인 : {np.shares_memory(arr,dap)}')
print(f'같은가 확인 : {arr is dap}')

메모리 공유 확인 : False
같은가 확인 : False


### reshape은 메모리를 공유하면서 변환

In [139]:
arr_1d = np.arange(12)
print(arr_1d)
arr_2d = arr_1d.reshape(3,4)

print(f'메모리 공유 확인: {np.shares_memory(arr_1d, arr_2d)}')      # reshape은 메모리를 공유함.
print(arr_1d is arr_2d)     # 모양은 확실히 다름.

print(arr_1d)
print(arr_2d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
메모리 공유 확인: True
False
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [145]:
a = np.array([
    [1,2,3]
])
print(f'a={a}')

b = np.array([
    [4,5,6]
])
print(f'b={b}')
print('--------------------')
print(np.r_[a,b])

v_row = np.vstack( [a,b] )
print(f'v_row: {v_row}')

print('--------------------')

concat_row = np.concatenate( (a,b), axis=0 )
print(f'concat_row: {concat_row}')

a=[[1 2 3]]
b=[[4 5 6]]
--------------------
[[1 2 3]
 [4 5 6]]
v_row: [[1 2 3]
 [4 5 6]]
--------------------
concat_row: [[1 2 3]
 [4 5 6]]


In [ ]:
a = np.array([
    [1,2,3]
])



In [147]:
a = np.array([1, 2, 3])
print(f'a={a}')                                # a=[1 2 3]

b = np.array([4, 5, 6])
print(f'b={b}')                                # b=[4 5 6]

print(np.c_[a,b])                              # [[1 4][2 5][3 6]]

h_col = np.hstack([a,b])
print(f'h_col:: {h_col}')                      # h_col:: [1 2 3 4 5 6]

# AxisError: axis 1 is out of bounds for array of dimension 1
concat_col = np.concatenate((a, b), axis=1)    # axis = 1

# 1차원일때는 concatenate 사용 불가

a=[1 2 3]
b=[4 5 6]
[[1 4]
 [2 5]
 [3 6]]
h_col:: [1 2 3 4 5 6]


AxisError: axis 1 is out of bounds for array of dimension 1

In [154]:
a = np.arange(12).reshape(3,4)
print(a)
x, y = np.split(a, 2, axis = 1)
print(x)
print(y)

'''
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]
'''

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


'\n[[ 0  1  2  3]\n [ 4  5  6  7]\n [ 8  9 10 11]]\n[[0 1]\n [4 5]\n [8 9]]\n[[ 2  3]\n [ 6  7]\n [10 11]]\n'

In [151]:
# 2차원이면 3차원으로 증가한다.
b = np.stack((x,y), axis = 0)
print(b.shape) # 2차원(m, n) => 3차원(2, m, n)
print(b)

'''
(2, 3, 2)
[[[ 0  1]
  [ 4  5]
  [ 8  9]]

 [[ 2  3]
  [ 6  7]
  [10 11]]]
'''

(2, 3, 2)
[[[ 0  1]
  [ 4  5]
  [ 8  9]]

 [[ 2  3]
  [ 6  7]
  [10 11]]]


'\n(2, 3, 2)\n[[[ 0  1]\n  [ 4  5]\n  [ 8  9]]\n\n [[ 2  3]\n  [ 6  7]\n  [10 11]]]\n'

In [159]:
b = np.stack((x,y), axis = 1)
print(b.shape) # 2차원(m, n) => 3차원(m,2, n)
print(b)

'''
[[0 1]
 [4 5]
 [8 9]]
 
[[ 2  3]
 [ 6  7]
 [10 11]]
  '''

(3, 2, 2)
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


'\n[[0 1]\n [4 5]\n [8 9]]\n\n[[ 2  3]\n [ 6  7]\n [10 11]]\n  '

In [160]:
c = np.concatenate((x, y), axis=0)
print(c.shape)
print(c)

'''
[[[ 0  1]
  [ 4  5]
  [ 8  9]]

 [[ 2  3]
  [ 6  7]
  [10 11]]]
 '''

(6, 2)
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [ 2  3]
 [ 6  7]
 [10 11]]


'\n[[[ 0  1]\n  [ 4  5]\n  [ 8  9]]\n\n [[ 2  3]\n  [ 6  7]\n  [10 11]]]\n '

In [158]:
c = np.concatenate((x, y), axis=1)
print(c.shape)
print(c)

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [162]:
x = np.arange(18)
print(f'x::{x}')

x = x.reshape(-1, 6)                # -1 : 행 갯수 자동 결정
print(f'x::{x}')

x::[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
x::[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [163]:
print(np.hsplit(x,3))
print( np.hsplit(x, (2,4)))

[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]


# Expanding Dimensions

In [165]:
arr = np.array([1,2,3])

row_vec = arr[np.newaxis, :]
print(arr)
print(row_vec)

[1 2 3]
[[1 2 3]]


In [171]:
col_vec = arr[:,np.newaxis]     # [3,] => [3,1]
print(col_vec)

[[1]
 [2]
 [3]]


## np.expand_dims(a, axis) = 명시적 차원 추가

In [172]:
import numpy as np

arr = np.array([1, 2, 3]) # shape: (3,)

# axis=0 위치에 차원 추가 -> shape: (1, 3)
e0 = np.expand_dims(arr, axis=0)

# axis=1 위치에 차원 추가 -> shape: (3, 1)
e1 = np.expand_dims(arr, axis=1)

print("e0.shape:", e0.shape) # (1, 3)
print("e1.shape:", e1.shape) # (3, 1)

e0.shape: (1, 3)
e1.shape: (3, 1)


## 차원 축소 : Squeezing

In [174]:
arr_3d = np.array([
    [
        [1], [2], [3]
    ]
])              # (1,3,1)


squeezed = np.squeeze(arr_3d)
print(squeezed)


[1 2 3]


ravel = 메모리 공유
flatten = 메모리 공유 X
reshqpe(-1) = 차원축소

In [175]:
d = np.array([[1, np.nan], 
              [3, 4]])

print(d)

[[ 1. nan]
 [ 3.  4.]]


## 백터화 연산과 브로드캐스팅  
- 작은걸 큰거에 맞춤

 **4) 암기 꿀팁 (헷갈릴 때 기억하는 방법)"지우개 법칙 (축을 없앤다!)"**

- `shape (3, 3)` 형태의 2차원 배열이 있을 때:
  - `axis=0`으로 연산하면 (3, 3)중  첫 번째 3(행 축)이 지워져 결과는 **`shape (3,)`** (세로 연산 결과)가 된다.
  - `axis=1`로 연산하면 (3, 3) 중 두 번째 3(열 축)이 지워져 결과는 **`shape (3,)`** (가로 연산 결과)가 된다.

즉, **`axis=n`은 "N번째 차원 방향으로 데이터들을 뭉개서 하나로 합친다!"** 라고 이해하시면 가장 쉽다.

## 3.5 위치 찾기: np.argmax(), np.argmin()을 활용한 최대/최소값의 인덱스 번호 추출

# 선형대수

In [179]:
import numpy as np

# 1. 백터 및 행렬 생성
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

A = np.array([
    [1,2],
    [3,4]
])


B = np.array([
    [5,6],
    [7,8]
])


# 2.백터 내적 (Dot Product)
dot_product = np.dot(v1,v2)
print(f'Vector Dot Product : {dot_product}')

Vector Dot Product : 32


In [ ]:
# 3.행렬 곱셈 (Matrix Multipliecation)
matrix_mul = np.matmul(A,B)
print('Matrix Multiplication (A @ B) :')

print(matrix_mul)

Matrix Multiplication (A @ B) :
[[19 22]
 [43 50]]


In [181]:
# 4.전치 행렬 (Transpose Matrix)
A_transpose = A.T
print('transpose of Matrix A : ')
print(A_transpose)

transpose of Matrix A : 
[[1 3]
 [2 4]]


배열은 @가능하지만 *은 사용 할 수 없다.

matrix는 * 와 @ 모두가 가능하다.

In [ ]:
c = np.matrix([[1,2], [3,4]]) # 행렬 생성
print(c)

print(c)
print(c.shape)

print(c * c.T)
print(c * np.dot(c.T))  # 함수방법으로 np.dot( )함수를 사용할 수 있다.
print( c.dot(c.T) ) # 메소드(method) 방식
print(c @ c.T)

'''
matrix([[ 5, 11],
        [11, 25]])
'''

In [184]:
import numpy as np

# 1. 시드 고정 및 가상의 학생 성적 데이터셋 생성 (학생 5명, 과목 3개)
np.random.seed(42)
scores = np.random.randint(40, 101, size=(5, 3))

print("1. 원본 성적 데이터셋 (5명 x 3과목):")
print(scores)

# 2. 각 과목별 평균 및 표준편차 구하기 (axis=0: 세로/열 방향 연산)
subject_mean = np.mean(scores, axis=0)
subject_std = np.std(scores, axis=0)

print("\n2. 과목별 평균:")
print(subject_mean)

print("\n3. 과목별 표준편차:")
print(np.round(subject_std, 2))

# 3. 각 학생별 평균 구하기 (axis=1: 가로/행 방향 연산)
student_mean = np.mean(scores, axis=1)

print("\n4. 학생별 평균 점수:")
print(np.round(student_mean, 2))

# 4. 낙제점 수정하기 (60점 미만인 점수를 60점으로 일괄 수정)
# np.where(조건, 참일 때 값, 거짓일 때 값) 활용
fixed_scores = np.where(scores < 60, 60, scores)

print("\n5. 낙제점(60점 미만) 수정 후 데이터셋:")
print(fixed_scores)

1. 원본 성적 데이터셋 (5명 x 3과목):
[[ 78  91  68]
 [ 54  82  47]
 [100  60  78]
 [ 97  58  62]
 [ 50  50  63]]

2. 과목별 평균:
[75.8 68.2 63.6]

3. 과목별 표준편차:
[20.88 15.57 10.05]

4. 학생별 평균 점수:
[79.   61.   79.33 72.33 54.33]

5. 낙제점(60점 미만) 수정 후 데이터셋:
[[ 78  91  68]
 [ 60  82  60]
 [100  60  78]
 [ 97  60  62]
 [ 60  60  63]]


In [185]:
import numpy as np

# 1. 가상의 RGB 이미지 픽셀 데이터 생성 (높이 4 x 너비 4 x 채널 3)
np.random.seed(100)
image_rgb = np.random.randint(0, 256, size=(4, 4, 3), dtype=np.uint8)

print("1. 원본 RGB 이미지 Shape:")
print(image_rgb.shape)

# 2. RGB 흑백 전환 (Grayscale Conversion)
# ITU-R BT.601 표준 공식: Y = 0.299*R + 0.587*G + 0.114*B
# 채널 축(axis 2)에 가중치를 내적(Dot Product)하거나 브로드캐스팅하여 계산함
weights = np.array([0.299, 0.587, 0.114])
image_gray = np.dot(image_rgb, weights).astype(np.uint8)

print("\n2. 흑백 전환 후 이미지 Shape:")
print(image_gray.shape)  # (4, 4)로 차원 축소됨

print("\n3. 흑백 이미지 픽셀 값:")
print(image_gray)

# 3. 이미지 크기 조절 (Downsampling / Resizing)
# 슬라이싱([::2, ::2])을 이용하여 가로/세로 픽셀을 2칸씩 스킵함으로써 크기를 1/2로 줄임
image_resized = image_gray[::2, ::2]

print("\n4. 크기 조절(2x2로 축소) 후 이미지 Shape:")
print(image_resized.shape)

print("\n5. 최종 축소된 이미지 픽셀 값:")
print(image_resized)

1. 원본 RGB 이미지 Shape:
(4, 4, 3)

2. 흑백 전환 후 이미지 Shape:
(4, 4)

3. 흑백 이미지 픽셀 값:
[[ 93  80 170  63]
 [175  87 124 128]
 [ 97 173  36  50]
 [ 89  73  33 139]]

4. 크기 조절(2x2로 축소) 후 이미지 Shape:
(2, 2)

5. 최종 축소된 이미지 픽셀 값:
[[ 93 170]
 [ 97  36]]
